language: csharp
mono: none
dotnet: 2.1.300
dist: trusty
sudo: required
os:
  - linux
  - osx

install:
  - dotnet restore
  - sudo lsof -i :5353

script:
  - dotnet build -c Release --no-restore --framework netstandard2 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp2 ./test
  - dotnet test  -c Release --no-restore --framework netcoreapp2.1 ./test
